### ISSUE TITLE
Läuft das bei jemanden?

### ISSUE THREAD

**Issue by ChrisHVL** [MakeMagazinDE/Wallbox-Steuerung#4]
Hallo Zusammen,
mit der Fernsteuerung der Wallbox ohne Shelly als Überschussladen habe ich kein Problem, da das Auto ja sowieso bei 100% abschaltet.
Mit der Arduino 2.03 IDE habe ich aber jede Menge Fehler in den Bibliotheken.
Was mache ich falsch?
Gibt es einen aktualisierten Code?
Danke!

**Comment by ChrisHVL** [comment]
Sehr schade, dass niemand auf die Anfragen beim Make-Magazin reagiert.
Kaufe mir jetzt den go-e - Controller. Der kostet zwar 250€, wird aber funktionieren...

**Comment by DiyParts** [comment]
Hallo ChrisHVK! Sehr schade, dass hier niemand vom Make Magazin (Redaktion/ Autor) geantwortet hat! 
Ich habe auch einen go-e Charger und PV und mich aus Interesse gerade erstmalig mit Schaltung und Software beschäftigt. Meine Erkenntnisse:
(1) Die Schaltung benötigt man nicht! Es gibt schon für 8€ in der Bucht einen IR Lese-/Sendekopf mit Schmitt-Triggern fertig bestückt. Ein Gehäuse findet man zum Drucken auch, dann sieht das auch nicht so gebastelt aus wie mit dem Flaschendeckel. Den RX Ausgang vom IR Lese-/Sendekopf muss man dann nur noch auf den esp8266 Eingang geben. LED und Taster drumherum - fertig ist die Schaltung.
(2) Ich habe hier einen EMH Zweirichtungszähler von meinem Energieversorger installiert bekommen. Dieser EMH gibt anstatt Textzeichen wie im "Infrarotkopf_pruefprogrammt_26.11.2021.ino" Daten im Hexformat aus. Dass es das auch gibt, ist im Artikel leider nicht beschrieben, das hätte mir helfen können. Jedenfalls hilft das Programm mir so nicht weiter, hier ist nur der einfachste Fall umgesetzt - das Leben hält andere Herausforderungen in der Hinterhand. Die unterschiedlichen Ausgabeformate werden hier prima vorgestellt: https://forum.arduino.cc/t/hello-world-sml-protokoll-auslesen/1199364. Ich habe daraufhin meine Forschung zum IR Kopf eingestellt und werde die Daten anders beschaffen müssen.
(3) Das Prüfprogramm kann man zunächst dafür nutzen, dass man Prüftexte über die Serial monitor view sendet. Dann sieht man schon ganz gut, was passiert, ohne dass der Lesekopf angeschlossen ist.
(4) Ich habe übrigens das Prüfprogramm dahingehend geändert, dass ich die eingelesenen Zeichen direkt auf die Serial Monitor view ausgebe (nach Zeile 54) und nicht erst im Nachhinein in der Funktion puffer_ausgeben(). In meinem Fall wurde der puffer beim Einlesen über den IR Kopf weder richtig angefangen, noch beendet. Daher wurde auch kein Puffer ausgegeben :-/
(5) Kommentare fehlen leider im Prüfprogramm. So auch hier:
#define LOGAREX 4 //D2 = GPIO4
Wenn ich mich nicht irre, soll hier die on board LED an- und ausgeknipst werden. Wäre interessant gewesen, dies anzumerken!!!! Bei meinem Wemos D1 m1n1 Clone sitzt die Led an GPIO2.

**Comment by ChrisHVL** [comment]
Hi DiyParts,der erste Kommentar überhaupt, das freut mich.Ich hatte bei der Make nachgefragt und dann hat mir der Chefredakteur geschrieben. Er hat sich für den Autor entschuldigt, schrieb aber auch, dass er keinerlei Möglichkeit hat, weiterzuhelfen, der Autor reagiert nämlich nicht mehr…Ich habe ja geschrieben, dass ich mir den go-e controller gekauft habe, der wartet zwar noch auf den Einbau, bei einem Freund läuft der aber schon und tut, was er soll. Außerdem ist der nicht vom Zähler abhängig. Der weitere Vorteil für mich ist, dass das eine Lösung ist, mit der auch andere Leute zurechtkommen.Wegen des Auslesens des Zählers: Kennst Du das:https://www.heise.de/tests/Ausprobiert-Guenstiger-IR-Lesekopf-fuer-Smart-Meter-mit-Tastmota-Firmware-7065559.htmlDer funktioniert tatsächlich, ist allerdings eher zum Verfolgen des Verbrauchs gedacht.VGChristian Schöldgen ***@***.***:  22.02.24 um 22:35 schrieb DiyParts
                
            
            
                
                    Von: "DiyParts" ***@***.***>Datum: 22. Februar 2024An: "MakeMagazinDE/Wallbox-Steuerung" ***@***.***>Cc: "Author" ***@***.***>,"ChrisHVL" ***@***.***>Betreff: Re: [MakeMagazinDE/Wallbox-Steuerung] Läuft das bei jemanden? (Issue #4)
                
                
Hallo ChrisHVK! Sehr schade, dass hier niemand vom Make Magazin (Redaktion/ Autor) geantwortet hat!
Ich habe auch einen go-e Charger und PV und mich aus Interesse gerade erstmalig mit Schaltung und Software beschäftigt. Meine Erkenntnisse:
(1) Die Schaltung benötigt man nicht! Es gibt schon für 8€ in der Bucht einen IR Lese-/Sendekopf mit Schmitt-Triggern fertig bestückt. Ein Gehäuse findet man zum Drucken auch, dann sieht das auch nicht so gebastelt aus wie mit dem Flaschendeckel. Den RX Ausgang vom IR Lese-/Sendekopf muss man dann nur noch auf den esp8266 Eingang geben. LED und Taster drumherum - fertig ist die Schaltung.
(2) Ich habe hier einen EMH Zweirichtungszähler von meinem Energieversorger installiert bekommen. Dieser EMH gibt anstatt Textzeichen wie im "Infrarotkopf_pruefprogrammt_26.11.2021.ino" Daten im Hexformat aus. Dass es das auch gibt, ist im Artikel leider nicht beschrieben, das hätte mir helfen können. Jedenfalls hilft das Programm mir so nicht weiter, hier ist nur der einfachste Fall umgesetzt - das Leben hält andere Herausforderungen in der Hinterhand. Die unterschiedlichen Ausgabeformate werden hier prima vorgestellt: https://forum.arduino.cc/t/hello-world-sml-protokoll-auslesen/1199364. Ich habe daraufhin meine Forschung zum IR Kopf eingestellt und werde die Daten anders beschaffen müssen.
(3) Das Prüfprogramm kann man zunächst dafür nutzen, dass man Prüftexte über die Serial monitor view sendet. Dann sieht man schon ganz gut, was passiert, ohne dass der Lesekopf angeschlossen ist.
(4) Ich habe übrigens das Prüfprogramm dahingehend geändert, dass ich die eingelesenen Zeichen direkt auf die Serial Monitor view ausgebe (nach Zeile 54) und nicht erst im Nachhinein in der Funktion puffer_ausgeben(). In meinem Fall wurde der puffer beim Einlesen über den IR Kopf weder richtig angefangen, noch beendet. Daher wurde auch kein Puffer ausgegeben :-/
(5) Kommentare fehlen leider im Prüfprogramm. So auch hier:
#define LOGAREX 4 //D2 = GPIO4
Wenn ich mich nicht irre, soll hier die on board LED an- und ausgeknipst werden. Wäre interessant gewesen, dies anzumerken!!!! Bei meinem Wemos D1 m1n1 Clone sitzt die Led an GPIO2.

**Comment by DiyParts** [comment]
Hallo Chris,
ich habe sowieso ein System am Laufen:
- Deye Hybridwechselrichter, Steuerung über CHINT DTSU666
- selbst gebauter Akku mit JKBMS 
- Kommunikation zwischen WR und Akku über https://github.com/ArminJo/JK-BMSToPylontechCAN

Ich wollte mit dem vorhandenen IR Kopf „mal schnell“ die Steuerung des go-e ausprobieren, bevor ich eine Steuerung des go-e in das Programm des JK-BMSToPylontechCAN Converters integriere. Das hat leider sowas von gar nicht geklappt 😊

Für mich ist damit aber der Weg vorgegeben: Ich werde den CHINT anzapfen und darüber den go-e charger steuern. Dann bin ich vom Zähler des Energieversorgers unabhängig.

Viele Grüße, Olaf
